-- Create user_roles table
CREATE TABLE IF NOT EXISTS user_roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_number TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('client', 'lawyer', 'admin', 'super_admin')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (id_number, role)
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_user_roles_id_number ON user_roles(id_number);

-- Migrate existing Clients
INSERT INTO user_roles (id_number, role)
SELECT DISTINCT id_number, 'client'
FROM users
WHERE id_number IS NOT NULL
ON CONFLICT (id_number, role) DO NOTHING;

-- Migrate existing Lawyers
INSERT INTO user_roles (id_number, role)
SELECT DISTINCT id_number, 'lawyer'
FROM lawyers
WHERE id_number IS NOT NULL
ON CONFLICT (id_number, role) DO NOTHING;

-- Migrate existing Admins
INSERT INTO user_roles (id_number, role)
SELECT DISTINCT id_number, 'admin'
FROM admins
WHERE id_number IS NOT NULL
ON CONFLICT (id_number, role) DO NOTHING;
